/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ESSENTIAL_SPACE_IDS: typeof import('./composables/useSpaceMarketplace')['ESSENTIAL_SPACE_IDS']
  const EffectScope: typeof import('vue')['EffectScope']
  const NATIVE_SPACE_IDS: typeof import('./composables/useSpaceMarketplace')['NATIVE_SPACE_IDS']
  const POPULAR_FONTS: typeof import('./composables/useGoogleFonts')['POPULAR_FONTS']
  const PRESET_LAYOUTS: typeof import('./composables/usePanelLayout')['PRESET_LAYOUTS']
  const SHORTCUT_REGISTRY: typeof import('./composables/useShortcutStore')['SHORTCUT_REGISTRY']
  const TELEMETRY_FEATURE_KEYS: typeof import('./composables/useTelemetry')['TELEMETRY_FEATURE_KEYS']
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const appConfig: typeof import('./utils/config')['appConfig']
  const appThemes: typeof import('./composables/useAppTheme')['appThemes']
  const asyncComputed: typeof import('@vueuse/core')['asyncComputed']
  const autoInstallRecommended: typeof import('./composables/useSpaceMarketplace')['autoInstallRecommended']
  const autoResetRef: typeof import('@vueuse/core')['autoResetRef']
  const buildCreateCommand: typeof import('./utils/templates.config')['buildCreateCommand']
  const buildProjectId: typeof import('./utils/projectRoutes')['buildProjectId']
  const buildProjectRoutePath: typeof import('./utils/projectRoutes')['buildProjectRoutePath']
  const buildProjectSpaceSubItems: typeof import('./utils/sidebarProjectNav')['buildProjectSpaceSubItems']
  const computed: typeof import('vue')['computed']
  const computedAsync: typeof import('@vueuse/core')['computedAsync']
  const computedEager: typeof import('@vueuse/core')['computedEager']
  const computedInject: typeof import('@vueuse/core')['computedInject']
  const computedWithControl: typeof import('@vueuse/core')['computedWithControl']
  const controlledComputed: typeof import('@vueuse/core')['controlledComputed']
  const controlledRef: typeof import('@vueuse/core')['controlledRef']
  const createApp: typeof import('vue')['createApp']
  const createEventHook: typeof import('@vueuse/core')['createEventHook']
  const createFolderPin: typeof import('./stores/pinned')['createFolderPin']
  const createGlobalState: typeof import('@vueuse/core')['createGlobalState']
  const createInjectionState: typeof import('@vueuse/core')['createInjectionState']
  const createLinkPin: typeof import('./stores/pinned')['createLinkPin']
  const createPagePin: typeof import('./stores/pinned')['createPagePin']
  const createPinia: typeof import('pinia')['createPinia']
  const createProjectPin: typeof import('./stores/pinned')['createProjectPin']
  const createReactiveFn: typeof import('@vueuse/core')['createReactiveFn']
  const createRef: typeof import('@vueuse/core')['createRef']
  const createReusableTemplate: typeof import('@vueuse/core')['createReusableTemplate']
  const createSharedComposable: typeof import('@vueuse/core')['createSharedComposable']
  const createSpacePin: typeof import('./stores/pinned')['createSpacePin']
  const createTaskPin: typeof import('./stores/pinned')['createTaskPin']
  const createTemplatePromise: typeof import('@vueuse/core')['createTemplatePromise']
  const createUnrefFn: typeof import('@vueuse/core')['createUnrefFn']
  const customRef: typeof import('vue')['customRef']
  const db: typeof import('./utils/db')['db']
  const debouncedRef: typeof import('@vueuse/core')['debouncedRef']
  const debouncedWatch: typeof import('@vueuse/core')['debouncedWatch']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const deleteDatabase: typeof import('./utils/db')['deleteDatabase']
  const detectTemplate: typeof import('./utils/templates.config')['detectTemplate']
  const docFilenameToTitle: typeof import('./composables/useAssistantData')['docFilenameToTitle']
  const docTitleToFilename: typeof import('./composables/useAssistantData')['docTitleToFilename']
  const eagerComputed: typeof import('@vueuse/core')['eagerComputed']
  const effectScope: typeof import('vue')['effectScope']
  const ensureEssentialSpaces: typeof import('./composables/useSpaceMarketplace')['ensureEssentialSpaces']
  const exportJson: typeof import('./composables/useShortcutStore')['exportJson']
  const extendRef: typeof import('@vueuse/core')['extendRef']
  const extractJson: typeof import('./utils/json-parse')['extractJson']
  const findFirstJsonArray: typeof import('./utils/json-parse')['findFirstJsonArray']
  const findFirstJsonObject: typeof import('./utils/json-parse')['findFirstJsonObject']
  const flattenCodeEditorTree: typeof import('./composables/useAssistantData')['flattenCodeEditorTree']
  const formatMissingToolsError: typeof import('./utils/templates.config')['formatMissingToolsError']
  const formatToolName: typeof import('./utils/parseReferences')['formatToolName']
  const formatToolResult: typeof import('./utils/parseReferences')['formatToolResult']
  const generateConstructConfig: typeof import('./utils/templates.config')['generateConstructConfig']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const getAppSpaces: typeof import('./composables/useSpaces')['getAppSpaces']
  const getConstructRuntime: typeof import('./composables/useConstructConfig')['getConstructRuntime']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getFileIcon: typeof import('./composables/useAssistantData')['getFileIcon']
  const getKey: typeof import('./composables/useShortcutStore')['getKey']
  const getLogger: typeof import('./composables/useLogger')['getLogger']
  const getProjectRouteKey: typeof import('./utils/projectRoutes')['getProjectRouteKey']
  const getProjectSpaces: typeof import('./composables/useSpaces')['getProjectSpaces']
  const getReferencedCodeFilesContext: typeof import('./utils/parseReferences')['getReferencedCodeFilesContext']
  const getReferencedComponentsContext: typeof import('./utils/parseReferences')['getReferencedComponentsContext']
  const getReferencedFilesContext: typeof import('./utils/parseReferences')['getReferencedFilesContext']
  const getRequiredTools: typeof import('./utils/templates.config')['getRequiredTools']
  const getTauriStore: typeof import('./composables/useTauriStore')['getTauriStore']
  const getTemplate: typeof import('./utils/templates.config')['getTemplate']
  const getTemplatesByCategory: typeof import('./utils/templates.config')['getTemplatesByCategory']
  const h: typeof import('vue')['h']
  const hasOverride: typeof import('./composables/useShortcutStore')['hasOverride']
  const ignorableWatch: typeof import('@vueuse/core')['ignorableWatch']
  const importJson: typeof import('./composables/useShortcutStore')['importJson']
  const inject: typeof import('vue')['inject']
  const injectLocal: typeof import('@vueuse/core')['injectLocal']
  const isDefined: typeof import('@vueuse/core')['isDefined']
  const isFontLoaded: typeof import('./composables/useGoogleFonts')['isFontLoaded']
  const isProjectRoutePath: typeof import('./utils/sidebarProjectNav')['isProjectRoutePath']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const isTauriEnv: typeof import('./utils/tauri')['isTauriEnv']
  const isTelemetryEnabled: typeof import('./composables/useTelemetry')['isTelemetryEnabled']
  const isVisionModel: typeof import('./composables/useAIModel')['isVisionModel']
  const loadGoogleFont: typeof import('./composables/useGoogleFonts')['loadGoogleFont']
  const makeDestructurable: typeof import('@vueuse/core')['makeDestructurable']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const markRaw: typeof import('vue')['markRaw']
  const migrateFromLocalStorage: typeof import('./composables/useStorage')['migrateFromLocalStorage']
  const migratePinnedItems: typeof import('./composables/useStorage')['migratePinnedItems']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onClickOutside: typeof import('@vueuse/core')['onClickOutside']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onElementRemoval: typeof import('@vueuse/core')['onElementRemoval']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onKeyStroke: typeof import('@vueuse/core')['onKeyStroke']
  const onLongPress: typeof import('@vueuse/core')['onLongPress']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onStartTyping: typeof import('@vueuse/core')['onStartTyping']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const openContextMenu: typeof import('./composables/useContextMenus')['openContextMenu']
  const parseCommandError: typeof import('./utils/templates.config')['parseCommandError']
  const parseJsonArray: typeof import('./utils/json-parse')['parseJsonArray']
  const parseJsonObject: typeof import('./utils/json-parse')['parseJsonObject']
  const parseProjectRouteContext: typeof import('./utils/sidebarProjectNav')['parseProjectRouteContext']
  const parseReferences: typeof import('./utils/parseReferences')['parseReferences']
  const pausableWatch: typeof import('@vueuse/core')['pausableWatch']
  const preloadCachedFonts: typeof import('./composables/useGoogleFonts')['preloadCachedFonts']
  const projectMatchesLookup: typeof import('./utils/projectRoutes')['projectMatchesLookup']
  const provide: typeof import('vue')['provide']
  const provideLocal: typeof import('@vueuse/core')['provideLocal']
  const randomFrom: typeof import('./utils/index')['randomFrom']
  const randomInt: typeof import('./utils/index')['randomInt']
  const reactify: typeof import('@vueuse/core')['reactify']
  const reactifyObject: typeof import('@vueuse/core')['reactifyObject']
  const reactive: typeof import('vue')['reactive']
  const reactiveComputed: typeof import('@vueuse/core')['reactiveComputed']
  const reactiveOmit: typeof import('@vueuse/core')['reactiveOmit']
  const reactivePick: typeof import('@vueuse/core')['reactivePick']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const refAutoReset: typeof import('@vueuse/core')['refAutoReset']
  const refDebounced: typeof import('@vueuse/core')['refDebounced']
  const refDefault: typeof import('@vueuse/core')['refDefault']
  const refManualReset: typeof import('@vueuse/core')['refManualReset']
  const refThrottled: typeof import('@vueuse/core')['refThrottled']
  const refWithControl: typeof import('@vueuse/core')['refWithControl']
  const registerContextMenuContributor: typeof import('./composables/useContextMenus')['registerContextMenuContributor']
  const renderMarkdown: typeof import('./composables/useMarkdown')['renderMarkdown']
  const renderStreamingMarkdown: typeof import('./composables/useMarkdown')['renderStreamingMarkdown']
  const resetAll: typeof import('./composables/useShortcutStore')['resetAll']
  const resetKey: typeof import('./composables/useShortcutStore')['resetKey']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const resolveContextMenuGroups: typeof import('./composables/useContextMenus')['resolveContextMenuGroups']
  const resolveRef: typeof import('@vueuse/core')['resolveRef']
  const routeParamString: typeof import('./utils/projectRoutes')['routeParamString']
  const sanitizeProjectName: typeof import('./utils/templates.config')['sanitizeProjectName']
  const searchFonts: typeof import('./composables/useGoogleFonts')['searchFonts']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setDockIcon: typeof import('./composables/useDockIcon')['setDockIcon']
  const setKey: typeof import('./composables/useShortcutStore')['setKey']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const setTelemetryConsent: typeof import('./composables/useTelemetry')['setTelemetryConsent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const showContextMenu: typeof import('./composables/useNativeContextMenu')['showContextMenu']
  const slugifyProjectToken: typeof import('./utils/projectRoutes')['slugifyProjectToken']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const syncRef: typeof import('@vueuse/core')['syncRef']
  const syncRefs: typeof import('@vueuse/core')['syncRefs']
  const taskPriorityColors: typeof import('./composables/useAssistantData')['taskPriorityColors']
  const taskStatusIcons: typeof import('./composables/useAssistantData')['taskStatusIcons']
  const templateRef: typeof import('@vueuse/core')['templateRef']
  const templates: typeof import('./utils/templates.config')['templates']
  const throttledRef: typeof import('@vueuse/core')['throttledRef']
  const throttledWatch: typeof import('@vueuse/core')['throttledWatch']
  const toRaw: typeof import('vue')['toRaw']
  const toReactive: typeof import('@vueuse/core')['toReactive']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const trackFeature: typeof import('./composables/useTelemetry')['trackFeature']
  const triggerRef: typeof import('vue')['triggerRef']
  const tryOnBeforeMount: typeof import('@vueuse/core')['tryOnBeforeMount']
  const tryOnBeforeUnmount: typeof import('@vueuse/core')['tryOnBeforeUnmount']
  const tryOnMounted: typeof import('@vueuse/core')['tryOnMounted']
  const tryOnScopeDispose: typeof import('@vueuse/core')['tryOnScopeDispose']
  const tryOnUnmounted: typeof import('@vueuse/core')['tryOnUnmounted']
  const unref: typeof import('vue')['unref']
  const unrefElement: typeof import('@vueuse/core')['unrefElement']
  const until: typeof import('@vueuse/core')['until']
  const useAIModel: typeof import('./composables/useAIModel')['useAIModel']
  const useActiveElement: typeof import('@vueuse/core')['useActiveElement']
  const useAnimate: typeof import('@vueuse/core')['useAnimate']
  const useApi: typeof import('./composables/useApi')['useApi']
  const useApiHealth: typeof import('./composables/useApiHealth')['useApiHealth']
  const useAppMenu: typeof import('./composables/useAppMenu')['useAppMenu']
  const useAppTheme: typeof import('./composables/useAppTheme')['useAppTheme']
  const useArrayDifference: typeof import('@vueuse/core')['useArrayDifference']
  const useArrayEvery: typeof import('@vueuse/core')['useArrayEvery']
  const useArrayFilter: typeof import('@vueuse/core')['useArrayFilter']
  const useArrayFind: typeof import('@vueuse/core')['useArrayFind']
  const useArrayFindIndex: typeof import('@vueuse/core')['useArrayFindIndex']
  const useArrayFindLast: typeof import('@vueuse/core')['useArrayFindLast']
  const useArrayIncludes: typeof import('@vueuse/core')['useArrayIncludes']
  const useArrayJoin: typeof import('@vueuse/core')['useArrayJoin']
  const useArrayMap: typeof import('@vueuse/core')['useArrayMap']
  const useArrayReduce: typeof import('@vueuse/core')['useArrayReduce']
  const useArraySome: typeof import('@vueuse/core')['useArraySome']
  const useArrayUnique: typeof import('@vueuse/core')['useArrayUnique']
  const useAssistantData: typeof import('./composables/useAssistantData')['useAssistantData']
  const useAsyncQueue: typeof import('@vueuse/core')['useAsyncQueue']
  const useAsyncState: typeof import('@vueuse/core')['useAsyncState']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAuth: typeof import('./composables/useAuth')['useAuth']
  const useAuthStore: typeof import('./stores/auth')['useAuthStore']
  const useAuthorization: typeof import('./composables/useAuthorization')['useAuthorization']
  const useBase64: typeof import('@vueuse/core')['useBase64']
  const useBasepodDeploy: typeof import('./composables/useBasepodDeploy')['useBasepodDeploy']
  const useBattery: typeof import('@vueuse/core')['useBattery']
  const useBilling: typeof import('./composables/useBilling')['useBilling']
  const useBluetooth: typeof import('@vueuse/core')['useBluetooth']
  const useBreakpoints: typeof import('@vueuse/core')['useBreakpoints']
  const useBroadcastChannel: typeof import('@vueuse/core')['useBroadcastChannel']
  const useBrowserLocation: typeof import('@vueuse/core')['useBrowserLocation']
  const useCached: typeof import('@vueuse/core')['useCached']
  const useClipboard: typeof import('@vueuse/core')['useClipboard']
  const useClipboardItems: typeof import('@vueuse/core')['useClipboardItems']
  const useCloned: typeof import('@vueuse/core')['useCloned']
  const useColorMode: typeof import('@vueuse/core')['useColorMode']
  const useConfirmDialog: typeof import('@vueuse/core')['useConfirmDialog']
  const useConstructAuth: typeof import('./composables/useConstructAuth')['useConstructAuth']
  const useConstructConfig: typeof import('./composables/useConstructConfig')['useConstructConfig']
  const useConstructWindow: typeof import('./composables/useConstructWindow')['useConstructWindow']
  const useContextDB: typeof import('./composables/useContextDB')['useContextDB']
  const useContextMenus: typeof import('./composables/useContextMenus')['useContextMenus']
  const useConversationsStore: typeof import('./stores/conversations')['useConversationsStore']
  const useCountdown: typeof import('@vueuse/core')['useCountdown']
  const useCounter: typeof import('@vueuse/core')['useCounter']
  const useCredits: typeof import('./composables/useCredits')['useCredits']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssSupports: typeof import('@vueuse/core')['useCssSupports']
  const useCssVar: typeof import('@vueuse/core')['useCssVar']
  const useCssVars: typeof import('vue')['useCssVars']
  const useCurrentElement: typeof import('@vueuse/core')['useCurrentElement']
  const useCycleList: typeof import('@vueuse/core')['useCycleList']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useDateFormat: typeof import('./composables/useDateFormat')['useDateFormat']
  const useDebounce: typeof import('@vueuse/core')['useDebounce']
  const useDebounceFn: typeof import('@vueuse/core')['useDebounceFn']
  const useDebouncedRefHistory: typeof import('@vueuse/core')['useDebouncedRefHistory']
  const useDeepLink: typeof import('./composables/useDeepLink')['useDeepLink']
  const useDevMode: typeof import('./composables/useDevMode')['useDevMode']
  const useDeviceMotion: typeof import('@vueuse/core')['useDeviceMotion']
  const useDeviceOrientation: typeof import('@vueuse/core')['useDeviceOrientation']
  const useDevicePixelRatio: typeof import('@vueuse/core')['useDevicePixelRatio']
  const useDevicesList: typeof import('@vueuse/core')['useDevicesList']
  const useDisplayMedia: typeof import('@vueuse/core')['useDisplayMedia']
  const useDocumentVisibility: typeof import('@vueuse/core')['useDocumentVisibility']
  const useDraggable: typeof import('@vueuse/core')['useDraggable']
  const useDraggableWindow: typeof import('./composables/useDraggableWindow')['useDraggableWindow']
  const useDropZone: typeof import('@vueuse/core')['useDropZone']
  const useDropdownPosition: typeof import('./composables/useDropdownPosition')['useDropdownPosition']
  const useElementBounding: typeof import('@vueuse/core')['useElementBounding']
  const useElementByPoint: typeof import('@vueuse/core')['useElementByPoint']
  const useElementHover: typeof import('@vueuse/core')['useElementHover']
  const useElementSize: typeof import('@vueuse/core')['useElementSize']
  const useElementVisibility: typeof import('@vueuse/core')['useElementVisibility']
  const useEventBus: typeof import('@vueuse/core')['useEventBus']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useEventSource: typeof import('@vueuse/core')['useEventSource']
  const useEyeDropper: typeof import('@vueuse/core')['useEyeDropper']
  const useFavicon: typeof import('@vueuse/core')['useFavicon']
  const useFetch: typeof import('@vueuse/core')['useFetch']
  const useFileDialog: typeof import('@vueuse/core')['useFileDialog']
  const useFileSystemAccess: typeof import('@vueuse/core')['useFileSystemAccess']
  const useFocus: typeof import('@vueuse/core')['useFocus']
  const useFocusWithin: typeof import('@vueuse/core')['useFocusWithin']
  const useFps: typeof import('@vueuse/core')['useFps']
  const useFullscreen: typeof import('@vueuse/core')['useFullscreen']
  const useGamepad: typeof import('@vueuse/core')['useGamepad']
  const useGeolocation: typeof import('@vueuse/core')['useGeolocation']
  const useGlobalShortcuts: typeof import('./composables/useGlobalShortcuts')['useGlobalShortcuts']
  const useGoogleFonts: typeof import('./composables/useGoogleFonts')['useGoogleFonts']
  const useId: typeof import('vue')['useId']
  const useIdle: typeof import('@vueuse/core')['useIdle']
  const useImage: typeof import('@vueuse/core')['useImage']
  const useInfiniteScroll: typeof import('@vueuse/core')['useInfiniteScroll']
  const useIntersectionObserver: typeof import('@vueuse/core')['useIntersectionObserver']
  const useInterval: typeof import('@vueuse/core')['useInterval']
  const useIntervalFn: typeof import('@vueuse/core')['useIntervalFn']
  const useKeyModifier: typeof import('@vueuse/core')['useKeyModifier']
  const useLastChanged: typeof import('@vueuse/core')['useLastChanged']
  const useLink: typeof import('vue-router')['useLink']
  const useLocalStorage: typeof import('@vueuse/core')['useLocalStorage']
  const useMagicKeys: typeof import('@vueuse/core')['useMagicKeys']
  const useManualRefHistory: typeof import('@vueuse/core')['useManualRefHistory']
  const useMarkdown: typeof import('./composables/useMarkdown')['useMarkdown']
  const useMediaControls: typeof import('@vueuse/core')['useMediaControls']
  const useMediaQuery: typeof import('@vueuse/core')['useMediaQuery']
  const useMemoize: typeof import('@vueuse/core')['useMemoize']
  const useMemory: typeof import('@vueuse/core')['useMemory']
  const useModel: typeof import('vue')['useModel']
  const useMounted: typeof import('@vueuse/core')['useMounted']
  const useMouse: typeof import('@vueuse/core')['useMouse']
  const useMouseInElement: typeof import('@vueuse/core')['useMouseInElement']
  const useMousePressed: typeof import('@vueuse/core')['useMousePressed']
  const useMutationObserver: typeof import('@vueuse/core')['useMutationObserver']
  const useNavigatorLanguage: typeof import('@vueuse/core')['useNavigatorLanguage']
  const useNetwork: typeof import('@vueuse/core')['useNetwork']
  const useNow: typeof import('@vueuse/core')['useNow']
  const useObjectUrl: typeof import('@vueuse/core')['useObjectUrl']
  const useOffsetPagination: typeof import('@vueuse/core')['useOffsetPagination']
  const useOnline: typeof import('@vueuse/core')['useOnline']
  const usePageLeave: typeof import('@vueuse/core')['usePageLeave']
  const usePanelLayout: typeof import('./composables/usePanelLayout')['usePanelLayout']
  const usePanelResize: typeof import('./composables/usePanelResize')['usePanelResize']
  const usePanels: typeof import('./composables/usePanels')['usePanels']
  const usePanelsStore: typeof import('./stores/panels')['usePanelsStore']
  const useParallax: typeof import('@vueuse/core')['useParallax']
  const useParentElement: typeof import('@vueuse/core')['useParentElement']
  const usePerformanceObserver: typeof import('@vueuse/core')['usePerformanceObserver']
  const usePermission: typeof import('@vueuse/core')['usePermission']
  const usePermissions: typeof import('./composables/usePermissions')['usePermissions']
  const usePinnedStore: typeof import('./stores/pinned')['usePinnedStore']
  const usePointer: typeof import('@vueuse/core')['usePointer']
  const usePointerLock: typeof import('@vueuse/core')['usePointerLock']
  const usePointerSwipe: typeof import('@vueuse/core')['usePointerSwipe']
  const usePreferencesStore: typeof import('./stores/preferences')['usePreferencesStore']
  const usePreferredColorScheme: typeof import('@vueuse/core')['usePreferredColorScheme']
  const usePreferredContrast: typeof import('@vueuse/core')['usePreferredContrast']
  const usePreferredDark: typeof import('@vueuse/core')['usePreferredDark']
  const usePreferredLanguages: typeof import('@vueuse/core')['usePreferredLanguages']
  const usePreferredReducedMotion: typeof import('@vueuse/core')['usePreferredReducedMotion']
  const usePreferredReducedTransparency: typeof import('@vueuse/core')['usePreferredReducedTransparency']
  const usePrevious: typeof import('@vueuse/core')['usePrevious']
  const useProjectContext: typeof import('./composables/useProjectContext')['useProjectContext']
  const useProjectDirectory: typeof import('./composables/useProjectDirectory')['useProjectDirectory']
  const useProjectStore: typeof import('./stores/project')['useProjectStore']
  const useProviderAuth: typeof import('./composables/useProviderAuth')['useProviderAuth']
  const useRafFn: typeof import('@vueuse/core')['useRafFn']
  const useRefHistory: typeof import('@vueuse/core')['useRefHistory']
  const useResizeObserver: typeof import('@vueuse/core')['useResizeObserver']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useSSRWidth: typeof import('@vueuse/core')['useSSRWidth']
  const useScreenOrientation: typeof import('@vueuse/core')['useScreenOrientation']
  const useScreenSafeArea: typeof import('@vueuse/core')['useScreenSafeArea']
  const useScriptTag: typeof import('@vueuse/core')['useScriptTag']
  const useScroll: typeof import('@vueuse/core')['useScroll']
  const useScrollLock: typeof import('@vueuse/core')['useScrollLock']
  const useSessionStorage: typeof import('@vueuse/core')['useSessionStorage']
  const useSettingsStore: typeof import('./stores/settings')['useSettingsStore']
  const useShare: typeof import('@vueuse/core')['useShare']
  const useShortcutStore: typeof import('./composables/useShortcutStore')['useShortcutStore']
  const useSidebar: typeof import('./composables/useSidebar')['useSidebar']
  const useSkills: typeof import('./composables/useSkills')['useSkills']
  const useSlots: typeof import('vue')['useSlots']
  const useSorted: typeof import('@vueuse/core')['useSorted']
  const useSource: typeof import('./composables/useSource')['useSource']
  const useSpaceAutoInstall: typeof import('./composables/useSpaceAutoInstall')['useSpaceAutoInstall']
  const useSpaceMarketplace: typeof import('./composables/useSpaceMarketplace')['useSpaceMarketplace']
  const useSpacePreview: typeof import('./composables/useSpacePreview')['useSpacePreview']
  const useSpaceShortcuts: typeof import('./composables/useSpaceShortcuts')['useSpaceShortcuts']
  const useSpaces: typeof import('./composables/useSpaces')['useSpaces']
  const useSpeechRecognition: typeof import('@vueuse/core')['useSpeechRecognition']
  const useSpeechSynthesis: typeof import('@vueuse/core')['useSpeechSynthesis']
  const useStepper: typeof import('@vueuse/core')['useStepper']
  const useStorage: typeof import('./composables/useStorage')['useStorage']
  const useStorageAsync: typeof import('@vueuse/core')['useStorageAsync']
  const useStyleTag: typeof import('@vueuse/core')['useStyleTag']
  const useSupported: typeof import('@vueuse/core')['useSupported']
  const useSwipe: typeof import('@vueuse/core')['useSwipe']
  const useTauriContext: typeof import('./composables/useTauriContext')['useTauriContext']
  const useTelemetry: typeof import('./composables/useTelemetry')['useTelemetry']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useTemplateRefsList: typeof import('@vueuse/core')['useTemplateRefsList']
  const useTextDirection: typeof import('@vueuse/core')['useTextDirection']
  const useTextSelection: typeof import('@vueuse/core')['useTextSelection']
  const useTextareaAutosize: typeof import('@vueuse/core')['useTextareaAutosize']
  const useThrottle: typeof import('@vueuse/core')['useThrottle']
  const useThrottleFn: typeof import('@vueuse/core')['useThrottleFn']
  const useThrottledRefHistory: typeof import('@vueuse/core')['useThrottledRefHistory']
  const useTimeAgo: typeof import('@vueuse/core')['useTimeAgo']
  const useTimeAgoIntl: typeof import('@vueuse/core')['useTimeAgoIntl']
  const useTimeout: typeof import('@vueuse/core')['useTimeout']
  const useTimeoutFn: typeof import('@vueuse/core')['useTimeoutFn']
  const useTimeoutPoll: typeof import('@vueuse/core')['useTimeoutPoll']
  const useTimestamp: typeof import('@vueuse/core')['useTimestamp']
  const useTitle: typeof import('@vueuse/core')['useTitle']
  const useToNumber: typeof import('@vueuse/core')['useToNumber']
  const useToString: typeof import('@vueuse/core')['useToString']
  const useToast: typeof import('./composables/useToast')['useToast']
  const useToggle: typeof import('@vueuse/core')['useToggle']
  const useToolbar: typeof import('./composables/useToolbar')['useToolbar']
  const useTransition: typeof import('@vueuse/core')['useTransition']
  const useUpdater: typeof import('./composables/useUpdater')['useUpdater']
  const useUrlSearchParams: typeof import('@vueuse/core')['useUrlSearchParams']
  const useUserMedia: typeof import('@vueuse/core')['useUserMedia']
  const useUserModule: typeof import('./composables/useUserModule')['useUserModule']
  const useVModel: typeof import('@vueuse/core')['useVModel']
  const useVModels: typeof import('@vueuse/core')['useVModels']
  const useVibrate: typeof import('@vueuse/core')['useVibrate']
  const useVirtualList: typeof import('@vueuse/core')['useVirtualList']
  const useWakeLock: typeof import('@vueuse/core')['useWakeLock']
  const useWebNotification: typeof import('@vueuse/core')['useWebNotification']
  const useWebSocket: typeof import('@vueuse/core')['useWebSocket']
  const useWebWorker: typeof import('@vueuse/core')['useWebWorker']
  const useWebWorkerFn: typeof import('@vueuse/core')['useWebWorkerFn']
  const useWindowChromeState: typeof import('./composables/useWindowChromeState')['useWindowChromeState']
  const useWindowFocus: typeof import('@vueuse/core')['useWindowFocus']
  const useWindowScroll: typeof import('@vueuse/core')['useWindowScroll']
  const useWindowSize: typeof import('@vueuse/core')['useWindowSize']
  const watch: typeof import('vue')['watch']
  const watchArray: typeof import('@vueuse/core')['watchArray']
  const watchAtMost: typeof import('@vueuse/core')['watchAtMost']
  const watchDebounced: typeof import('@vueuse/core')['watchDebounced']
  const watchDeep: typeof import('@vueuse/core')['watchDeep']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchIgnorable: typeof import('@vueuse/core')['watchIgnorable']
  const watchImmediate: typeof import('@vueuse/core')['watchImmediate']
  const watchOnce: typeof import('@vueuse/core')['watchOnce']
  const watchPausable: typeof import('@vueuse/core')['watchPausable']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const watchThrottled: typeof import('@vueuse/core')['watchThrottled']
  const watchTriggerable: typeof import('@vueuse/core')['watchTriggerable']
  const watchWithFilter: typeof import('@vueuse/core')['watchWithFilter']
  const whenever: typeof import('@vueuse/core')['whenever']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AuthType, AIModelOption } from './composables/useAIModel'
  import('./composables/useAIModel')
  // @ts-ignore
  export type { ApiHealthState } from './composables/useApiHealth'
  import('./composables/useApiHealth')
  // @ts-ignore
  export type { AppTheme } from './composables/useAppTheme'
  import('./composables/useAppTheme')
  // @ts-ignore
  export type { DeployedApp } from './composables/useBasepodDeploy'
  import('./composables/useBasepodDeploy')
  // @ts-ignore
  export type { BillingPlan, BillingSubscription, BillingInvoice } from './composables/useBilling'
  import('./composables/useBilling')
  // @ts-ignore
  export type { ConstructWindowOptions, ConstructWindow } from './composables/useConstructWindow'
  import('./composables/useConstructWindow')
  // @ts-ignore
  export type { ContextUIDesign, ContextProjectSettings, KVEntry, AIConversation } from './composables/useContextDB'
  import('./composables/useContextDB')
  // @ts-ignore
  export type { CreditPool, CreditTransaction, CreditPackage, CreditsSummary, CreditBalance, PurchaseCreditsRequest } from './composables/useCredits'
  import('./composables/useCredits')
  // @ts-ignore
  export type { DockIconState } from './composables/useDockIcon'
  import('./composables/useDockIcon')
  // @ts-ignore
  export type { WindowState, DraggableWindowOptions } from './composables/useDraggableWindow'
  import('./composables/useDraggableWindow')
  // @ts-ignore
  export type { GoogleFont } from './composables/useGoogleFonts'
  import('./composables/useGoogleFonts')
  // @ts-ignore
  export type { NativeMenuOption, NativeMenuGroup } from './composables/useNativeContextMenu'
  import('./composables/useNativeContextMenu')
  // @ts-ignore
  export type { ResizablePanelConfig, SpaceLayoutConfig } from './composables/usePanelLayout'
  import('./composables/usePanelLayout')
  // @ts-ignore
  export type { UsePanelResizeOptions } from './composables/usePanelResize'
  import('./composables/usePanelResize')
  // @ts-ignore
  export type { ProjectConfig, ProjectDirectoryEntry } from './composables/useProjectDirectory'
  import('./composables/useProjectDirectory')
  // @ts-ignore
  export type { ShortcutSpace, ShortcutDef } from './composables/useShortcutStore'
  import('./composables/useShortcutStore')
  // @ts-ignore
  export type { SidebarPanel, SpaceNavItem, ProjectSpaceNavItem, SidebarNavItem } from './composables/useSidebar'
  import('./composables/useSidebar')
  // @ts-ignore
  export type { SkillInfo, HookInfo, SkillMetrics, HookMetrics, SkillSummary, SkillContent, ToolDefinition, HookDefinition, ParameterDefinition, SkillExample, SkillMatch, SkillSearchQuery, SkillSearchResult } from './composables/useSkills'
  import('./composables/useSkills')
  // @ts-ignore
  export type { RemoteSpace, InstalledSpace } from './composables/useSpaceMarketplace'
  import('./composables/useSpaceMarketplace')
  // @ts-ignore
  export type { SpaceShortcut } from './composables/useSpaceShortcuts'
  import('./composables/useSpaceShortcuts')
  // @ts-ignore
  export type { SpaceToolbarItem, SpacePage, SpaceConfig } from './composables/useSpaces'
  import('./composables/useSpaces')
  // @ts-ignore
  export type { StorageOptions, StorageItem, UseStorageReturn } from './composables/useStorage'
  import('./composables/useStorage')
  // @ts-ignore
  export type { TelemetryFeatureKey } from './composables/useTelemetry'
  import('./composables/useTelemetry')
  // @ts-ignore
  export type { Toast } from './composables/useToast'
  import('./composables/useToast')
  // @ts-ignore
  export type { ToolbarItem, ToolbarBreadcrumb } from './composables/useToolbar'
  import('./composables/useToolbar')
  // @ts-ignore
  export type { UpdateInfo } from './composables/useUpdater'
  import('./composables/useUpdater')
  // @ts-ignore
  export type { UserModuleState } from './composables/useUserModule'
  import('./composables/useUserModule')
  // @ts-ignore
  export type { Conversation } from './stores/conversations'
  import('./stores/conversations')
  // @ts-ignore
  export type { PinnedItem } from './stores/pinned'
  import('./stores/pinned')
  // @ts-ignore
  export type { Project } from './stores/project'
  import('./stores/project')
  // @ts-ignore
  export type { ProjectLocalSettings } from './utils/db'
  import('./utils/db')
  // @ts-ignore
  export type { FileReference, DocReference, ParsedReferences } from './utils/parseReferences'
  import('./utils/parseReferences')
  // @ts-ignore
  export type { ProjectRouteCandidate } from './utils/projectRoutes'
  import('./utils/projectRoutes')
  // @ts-ignore
  export type { ProjectRouteContext, SpacePageLike, SpaceLike, SidebarSubItem } from './utils/sidebarProjectNav'
  import('./utils/sidebarProjectNav')
  // @ts-ignore
  export type { TemplateCommand, TemplateModule, RequiredTool, TemplateConfig, ConstructProjectConfig, MissingToolError } from './utils/templates.config'
  import('./utils/templates.config')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ESSENTIAL_SPACE_IDS: UnwrapRef<typeof import('./composables/useSpaceMarketplace')['ESSENTIAL_SPACE_IDS']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly NATIVE_SPACE_IDS: UnwrapRef<typeof import('./composables/useSpaceMarketplace')['NATIVE_SPACE_IDS']>
    readonly POPULAR_FONTS: UnwrapRef<typeof import('./composables/useGoogleFonts')['POPULAR_FONTS']>
    readonly PRESET_LAYOUTS: UnwrapRef<typeof import('./composables/usePanelLayout')['PRESET_LAYOUTS']>
    readonly SHORTCUT_REGISTRY: UnwrapRef<typeof import('./composables/useShortcutStore')['SHORTCUT_REGISTRY']>
    readonly TELEMETRY_FEATURE_KEYS: UnwrapRef<typeof import('./composables/useTelemetry')['TELEMETRY_FEATURE_KEYS']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly appConfig: UnwrapRef<typeof import('./utils/config')['appConfig']>
    readonly appThemes: UnwrapRef<typeof import('./composables/useAppTheme')['appThemes']>
    readonly asyncComputed: UnwrapRef<typeof import('@vueuse/core')['asyncComputed']>
    readonly autoInstallRecommended: UnwrapRef<typeof import('./composables/useSpaceMarketplace')['autoInstallRecommended']>
    readonly autoResetRef: UnwrapRef<typeof import('@vueuse/core')['autoResetRef']>
    readonly buildCreateCommand: UnwrapRef<typeof import('./utils/templates.config')['buildCreateCommand']>
    readonly buildProjectId: UnwrapRef<typeof import('./utils/projectRoutes')['buildProjectId']>
    readonly buildProjectRoutePath: UnwrapRef<typeof import('./utils/projectRoutes')['buildProjectRoutePath']>
    readonly buildProjectSpaceSubItems: UnwrapRef<typeof import('./utils/sidebarProjectNav')['buildProjectSpaceSubItems']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly computedAsync: UnwrapRef<typeof import('@vueuse/core')['computedAsync']>
    readonly computedEager: UnwrapRef<typeof import('@vueuse/core')['computedEager']>
    readonly computedInject: UnwrapRef<typeof import('@vueuse/core')['computedInject']>
    readonly computedWithControl: UnwrapRef<typeof import('@vueuse/core')['computedWithControl']>
    readonly controlledComputed: UnwrapRef<typeof import('@vueuse/core')['controlledComputed']>
    readonly controlledRef: UnwrapRef<typeof import('@vueuse/core')['controlledRef']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createEventHook: UnwrapRef<typeof import('@vueuse/core')['createEventHook']>
    readonly createFolderPin: UnwrapRef<typeof import('./stores/pinned')['createFolderPin']>
    readonly createGlobalState: UnwrapRef<typeof import('@vueuse/core')['createGlobalState']>
    readonly createInjectionState: UnwrapRef<typeof import('@vueuse/core')['createInjectionState']>
    readonly createLinkPin: UnwrapRef<typeof import('./stores/pinned')['createLinkPin']>
    readonly createPagePin: UnwrapRef<typeof import('./stores/pinned')['createPagePin']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly createProjectPin: UnwrapRef<typeof import('./stores/pinned')['createProjectPin']>
    readonly createReactiveFn: UnwrapRef<typeof import('@vueuse/core')['createReactiveFn']>
    readonly createRef: UnwrapRef<typeof import('@vueuse/core')['createRef']>
    readonly createReusableTemplate: UnwrapRef<typeof import('@vueuse/core')['createReusableTemplate']>
    readonly createSharedComposable: UnwrapRef<typeof import('@vueuse/core')['createSharedComposable']>
    readonly createSpacePin: UnwrapRef<typeof import('./stores/pinned')['createSpacePin']>
    readonly createTaskPin: UnwrapRef<typeof import('./stores/pinned')['createTaskPin']>
    readonly createTemplatePromise: UnwrapRef<typeof import('@vueuse/core')['createTemplatePromise']>
    readonly createUnrefFn: UnwrapRef<typeof import('@vueuse/core')['createUnrefFn']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly db: UnwrapRef<typeof import('./utils/db')['db']>
    readonly debouncedRef: UnwrapRef<typeof import('@vueuse/core')['debouncedRef']>
    readonly debouncedWatch: UnwrapRef<typeof import('@vueuse/core')['debouncedWatch']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly deleteDatabase: UnwrapRef<typeof import('./utils/db')['deleteDatabase']>
    readonly detectTemplate: UnwrapRef<typeof import('./utils/templates.config')['detectTemplate']>
    readonly docFilenameToTitle: UnwrapRef<typeof import('./composables/useAssistantData')['docFilenameToTitle']>
    readonly docTitleToFilename: UnwrapRef<typeof import('./composables/useAssistantData')['docTitleToFilename']>
    readonly eagerComputed: UnwrapRef<typeof import('@vueuse/core')['eagerComputed']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly ensureEssentialSpaces: UnwrapRef<typeof import('./composables/useSpaceMarketplace')['ensureEssentialSpaces']>
    readonly exportJson: UnwrapRef<typeof import('./composables/useShortcutStore')['exportJson']>
    readonly extendRef: UnwrapRef<typeof import('@vueuse/core')['extendRef']>
    readonly extractJson: UnwrapRef<typeof import('./utils/json-parse')['extractJson']>
    readonly findFirstJsonArray: UnwrapRef<typeof import('./utils/json-parse')['findFirstJsonArray']>
    readonly findFirstJsonObject: UnwrapRef<typeof import('./utils/json-parse')['findFirstJsonObject']>
    readonly flattenCodeEditorTree: UnwrapRef<typeof import('./composables/useAssistantData')['flattenCodeEditorTree']>
    readonly formatMissingToolsError: UnwrapRef<typeof import('./utils/templates.config')['formatMissingToolsError']>
    readonly formatToolName: UnwrapRef<typeof import('./utils/parseReferences')['formatToolName']>
    readonly formatToolResult: UnwrapRef<typeof import('./utils/parseReferences')['formatToolResult']>
    readonly generateConstructConfig: UnwrapRef<typeof import('./utils/templates.config')['generateConstructConfig']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getAppSpaces: UnwrapRef<typeof import('./composables/useSpaces')['getAppSpaces']>
    readonly getConstructRuntime: UnwrapRef<typeof import('./composables/useConstructConfig')['getConstructRuntime']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getFileIcon: UnwrapRef<typeof import('./composables/useAssistantData')['getFileIcon']>
    readonly getKey: UnwrapRef<typeof import('./composables/useShortcutStore')['getKey']>
    readonly getLogger: UnwrapRef<typeof import('./composables/useLogger')['getLogger']>
    readonly getProjectRouteKey: UnwrapRef<typeof import('./utils/projectRoutes')['getProjectRouteKey']>
    readonly getProjectSpaces: UnwrapRef<typeof import('./composables/useSpaces')['getProjectSpaces']>
    readonly getReferencedCodeFilesContext: UnwrapRef<typeof import('./utils/parseReferences')['getReferencedCodeFilesContext']>
    readonly getReferencedComponentsContext: UnwrapRef<typeof import('./utils/parseReferences')['getReferencedComponentsContext']>
    readonly getReferencedFilesContext: UnwrapRef<typeof import('./utils/parseReferences')['getReferencedFilesContext']>
    readonly getRequiredTools: UnwrapRef<typeof import('./utils/templates.config')['getRequiredTools']>
    readonly getTauriStore: UnwrapRef<typeof import('./composables/useTauriStore')['getTauriStore']>
    readonly getTemplate: UnwrapRef<typeof import('./utils/templates.config')['getTemplate']>
    readonly getTemplatesByCategory: UnwrapRef<typeof import('./utils/templates.config')['getTemplatesByCategory']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hasOverride: UnwrapRef<typeof import('./composables/useShortcutStore')['hasOverride']>
    readonly ignorableWatch: UnwrapRef<typeof import('@vueuse/core')['ignorableWatch']>
    readonly importJson: UnwrapRef<typeof import('./composables/useShortcutStore')['importJson']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectLocal: UnwrapRef<typeof import('@vueuse/core')['injectLocal']>
    readonly isDefined: UnwrapRef<typeof import('@vueuse/core')['isDefined']>
    readonly isFontLoaded: UnwrapRef<typeof import('./composables/useGoogleFonts')['isFontLoaded']>
    readonly isProjectRoutePath: UnwrapRef<typeof import('./utils/sidebarProjectNav')['isProjectRoutePath']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isTauriEnv: UnwrapRef<typeof import('./utils/tauri')['isTauriEnv']>
    readonly isTelemetryEnabled: UnwrapRef<typeof import('./composables/useTelemetry')['isTelemetryEnabled']>
    readonly isVisionModel: UnwrapRef<typeof import('./composables/useAIModel')['isVisionModel']>
    readonly loadGoogleFont: UnwrapRef<typeof import('./composables/useGoogleFonts')['loadGoogleFont']>
    readonly makeDestructurable: UnwrapRef<typeof import('@vueuse/core')['makeDestructurable']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly migrateFromLocalStorage: UnwrapRef<typeof import('./composables/useStorage')['migrateFromLocalStorage']>
    readonly migratePinnedItems: UnwrapRef<typeof import('./composables/useStorage')['migratePinnedItems']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onClickOutside: UnwrapRef<typeof import('@vueuse/core')['onClickOutside']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onElementRemoval: UnwrapRef<typeof import('@vueuse/core')['onElementRemoval']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onKeyStroke: UnwrapRef<typeof import('@vueuse/core')['onKeyStroke']>
    readonly onLongPress: UnwrapRef<typeof import('@vueuse/core')['onLongPress']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onStartTyping: UnwrapRef<typeof import('@vueuse/core')['onStartTyping']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly openContextMenu: UnwrapRef<typeof import('./composables/useContextMenus')['openContextMenu']>
    readonly parseCommandError: UnwrapRef<typeof import('./utils/templates.config')['parseCommandError']>
    readonly parseJsonArray: UnwrapRef<typeof import('./utils/json-parse')['parseJsonArray']>
    readonly parseJsonObject: UnwrapRef<typeof import('./utils/json-parse')['parseJsonObject']>
    readonly parseProjectRouteContext: UnwrapRef<typeof import('./utils/sidebarProjectNav')['parseProjectRouteContext']>
    readonly parseReferences: UnwrapRef<typeof import('./utils/parseReferences')['parseReferences']>
    readonly pausableWatch: UnwrapRef<typeof import('@vueuse/core')['pausableWatch']>
    readonly preloadCachedFonts: UnwrapRef<typeof import('./composables/useGoogleFonts')['preloadCachedFonts']>
    readonly projectMatchesLookup: UnwrapRef<typeof import('./utils/projectRoutes')['projectMatchesLookup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly provideLocal: UnwrapRef<typeof import('@vueuse/core')['provideLocal']>
    readonly randomFrom: UnwrapRef<typeof import('./utils/index')['randomFrom']>
    readonly randomInt: UnwrapRef<typeof import('./utils/index')['randomInt']>
    readonly reactify: UnwrapRef<typeof import('@vueuse/core')['reactify']>
    readonly reactifyObject: UnwrapRef<typeof import('@vueuse/core')['reactifyObject']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly reactiveComputed: UnwrapRef<typeof import('@vueuse/core')['reactiveComputed']>
    readonly reactiveOmit: UnwrapRef<typeof import('@vueuse/core')['reactiveOmit']>
    readonly reactivePick: UnwrapRef<typeof import('@vueuse/core')['reactivePick']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refAutoReset: UnwrapRef<typeof import('@vueuse/core')['refAutoReset']>
    readonly refDebounced: UnwrapRef<typeof import('@vueuse/core')['refDebounced']>
    readonly refDefault: UnwrapRef<typeof import('@vueuse/core')['refDefault']>
    readonly refManualReset: UnwrapRef<typeof import('@vueuse/core')['refManualReset']>
    readonly refThrottled: UnwrapRef<typeof import('@vueuse/core')['refThrottled']>
    readonly refWithControl: UnwrapRef<typeof import('@vueuse/core')['refWithControl']>
    readonly registerContextMenuContributor: UnwrapRef<typeof import('./composables/useContextMenus')['registerContextMenuContributor']>
    readonly renderMarkdown: UnwrapRef<typeof import('./composables/useMarkdown')['renderMarkdown']>
    readonly renderStreamingMarkdown: UnwrapRef<typeof import('./composables/useMarkdown')['renderStreamingMarkdown']>
    readonly resetAll: UnwrapRef<typeof import('./composables/useShortcutStore')['resetAll']>
    readonly resetKey: UnwrapRef<typeof import('./composables/useShortcutStore')['resetKey']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolveContextMenuGroups: UnwrapRef<typeof import('./composables/useContextMenus')['resolveContextMenuGroups']>
    readonly resolveRef: UnwrapRef<typeof import('@vueuse/core')['resolveRef']>
    readonly routeParamString: UnwrapRef<typeof import('./utils/projectRoutes')['routeParamString']>
    readonly sanitizeProjectName: UnwrapRef<typeof import('./utils/templates.config')['sanitizeProjectName']>
    readonly searchFonts: UnwrapRef<typeof import('./composables/useGoogleFonts')['searchFonts']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setDockIcon: UnwrapRef<typeof import('./composables/useDockIcon')['setDockIcon']>
    readonly setKey: UnwrapRef<typeof import('./composables/useShortcutStore')['setKey']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly setTelemetryConsent: UnwrapRef<typeof import('./composables/useTelemetry')['setTelemetryConsent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly showContextMenu: UnwrapRef<typeof import('./composables/useNativeContextMenu')['showContextMenu']>
    readonly slugifyProjectToken: UnwrapRef<typeof import('./utils/projectRoutes')['slugifyProjectToken']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly syncRef: UnwrapRef<typeof import('@vueuse/core')['syncRef']>
    readonly syncRefs: UnwrapRef<typeof import('@vueuse/core')['syncRefs']>
    readonly taskPriorityColors: UnwrapRef<typeof import('./composables/useAssistantData')['taskPriorityColors']>
    readonly taskStatusIcons: UnwrapRef<typeof import('./composables/useAssistantData')['taskStatusIcons']>
    readonly templateRef: UnwrapRef<typeof import('@vueuse/core')['templateRef']>
    readonly templates: UnwrapRef<typeof import('./utils/templates.config')['templates']>
    readonly throttledRef: UnwrapRef<typeof import('@vueuse/core')['throttledRef']>
    readonly throttledWatch: UnwrapRef<typeof import('@vueuse/core')['throttledWatch']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toReactive: UnwrapRef<typeof import('@vueuse/core')['toReactive']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly trackFeature: UnwrapRef<typeof import('./composables/useTelemetry')['trackFeature']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly tryOnBeforeMount: UnwrapRef<typeof import('@vueuse/core')['tryOnBeforeMount']>
    readonly tryOnBeforeUnmount: UnwrapRef<typeof import('@vueuse/core')['tryOnBeforeUnmount']>
    readonly tryOnMounted: UnwrapRef<typeof import('@vueuse/core')['tryOnMounted']>
    readonly tryOnScopeDispose: UnwrapRef<typeof import('@vueuse/core')['tryOnScopeDispose']>
    readonly tryOnUnmounted: UnwrapRef<typeof import('@vueuse/core')['tryOnUnmounted']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly unrefElement: UnwrapRef<typeof import('@vueuse/core')['unrefElement']>
    readonly until: UnwrapRef<typeof import('@vueuse/core')['until']>
    readonly useAIModel: UnwrapRef<typeof import('./composables/useAIModel')['useAIModel']>
    readonly useActiveElement: UnwrapRef<typeof import('@vueuse/core')['useActiveElement']>
    readonly useAnimate: UnwrapRef<typeof import('@vueuse/core')['useAnimate']>
    readonly useApi: UnwrapRef<typeof import('./composables/useApi')['useApi']>
    readonly useApiHealth: UnwrapRef<typeof import('./composables/useApiHealth')['useApiHealth']>
    readonly useAppMenu: UnwrapRef<typeof import('./composables/useAppMenu')['useAppMenu']>
    readonly useAppTheme: UnwrapRef<typeof import('./composables/useAppTheme')['useAppTheme']>
    readonly useArrayDifference: UnwrapRef<typeof import('@vueuse/core')['useArrayDifference']>
    readonly useArrayEvery: UnwrapRef<typeof import('@vueuse/core')['useArrayEvery']>
    readonly useArrayFilter: UnwrapRef<typeof import('@vueuse/core')['useArrayFilter']>
    readonly useArrayFind: UnwrapRef<typeof import('@vueuse/core')['useArrayFind']>
    readonly useArrayFindIndex: UnwrapRef<typeof import('@vueuse/core')['useArrayFindIndex']>
    readonly useArrayFindLast: UnwrapRef<typeof import('@vueuse/core')['useArrayFindLast']>
    readonly useArrayIncludes: UnwrapRef<typeof import('@vueuse/core')['useArrayIncludes']>
    readonly useArrayJoin: UnwrapRef<typeof import('@vueuse/core')['useArrayJoin']>
    readonly useArrayMap: UnwrapRef<typeof import('@vueuse/core')['useArrayMap']>
    readonly useArrayReduce: UnwrapRef<typeof import('@vueuse/core')['useArrayReduce']>
    readonly useArraySome: UnwrapRef<typeof import('@vueuse/core')['useArraySome']>
    readonly useArrayUnique: UnwrapRef<typeof import('@vueuse/core')['useArrayUnique']>
    readonly useAssistantData: UnwrapRef<typeof import('./composables/useAssistantData')['useAssistantData']>
    readonly useAsyncQueue: UnwrapRef<typeof import('@vueuse/core')['useAsyncQueue']>
    readonly useAsyncState: UnwrapRef<typeof import('@vueuse/core')['useAsyncState']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuth: UnwrapRef<typeof import('./composables/useAuth')['useAuth']>
    readonly useAuthStore: UnwrapRef<typeof import('./stores/auth')['useAuthStore']>
    readonly useAuthorization: UnwrapRef<typeof import('./composables/useAuthorization')['useAuthorization']>
    readonly useBase64: UnwrapRef<typeof import('@vueuse/core')['useBase64']>
    readonly useBasepodDeploy: UnwrapRef<typeof import('./composables/useBasepodDeploy')['useBasepodDeploy']>
    readonly useBattery: UnwrapRef<typeof import('@vueuse/core')['useBattery']>
    readonly useBilling: UnwrapRef<typeof import('./composables/useBilling')['useBilling']>
    readonly useBluetooth: UnwrapRef<typeof import('@vueuse/core')['useBluetooth']>
    readonly useBreakpoints: UnwrapRef<typeof import('@vueuse/core')['useBreakpoints']>
    readonly useBroadcastChannel: UnwrapRef<typeof import('@vueuse/core')['useBroadcastChannel']>
    readonly useBrowserLocation: UnwrapRef<typeof import('@vueuse/core')['useBrowserLocation']>
    readonly useCached: UnwrapRef<typeof import('@vueuse/core')['useCached']>
    readonly useClipboard: UnwrapRef<typeof import('@vueuse/core')['useClipboard']>
    readonly useClipboardItems: UnwrapRef<typeof import('@vueuse/core')['useClipboardItems']>
    readonly useCloned: UnwrapRef<typeof import('@vueuse/core')['useCloned']>
    readonly useColorMode: UnwrapRef<typeof import('@vueuse/core')['useColorMode']>
    readonly useConfirmDialog: UnwrapRef<typeof import('@vueuse/core')['useConfirmDialog']>
    readonly useConstructAuth: UnwrapRef<typeof import('./composables/useConstructAuth')['useConstructAuth']>
    readonly useConstructConfig: UnwrapRef<typeof import('./composables/useConstructConfig')['useConstructConfig']>
    readonly useConstructWindow: UnwrapRef<typeof import('./composables/useConstructWindow')['useConstructWindow']>
    readonly useContextDB: UnwrapRef<typeof import('./composables/useContextDB')['useContextDB']>
    readonly useContextMenus: UnwrapRef<typeof import('./composables/useContextMenus')['useContextMenus']>
    readonly useConversationsStore: UnwrapRef<typeof import('./stores/conversations')['useConversationsStore']>
    readonly useCountdown: UnwrapRef<typeof import('@vueuse/core')['useCountdown']>
    readonly useCounter: UnwrapRef<typeof import('@vueuse/core')['useCounter']>
    readonly useCredits: UnwrapRef<typeof import('./composables/useCredits')['useCredits']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssSupports: UnwrapRef<typeof import('@vueuse/core')['useCssSupports']>
    readonly useCssVar: UnwrapRef<typeof import('@vueuse/core')['useCssVar']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useCurrentElement: UnwrapRef<typeof import('@vueuse/core')['useCurrentElement']>
    readonly useCycleList: UnwrapRef<typeof import('@vueuse/core')['useCycleList']>
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>
    readonly useDateFormat: UnwrapRef<typeof import('./composables/useDateFormat')['useDateFormat']>
    readonly useDebounce: UnwrapRef<typeof import('@vueuse/core')['useDebounce']>
    readonly useDebounceFn: UnwrapRef<typeof import('@vueuse/core')['useDebounceFn']>
    readonly useDebouncedRefHistory: UnwrapRef<typeof import('@vueuse/core')['useDebouncedRefHistory']>
    readonly useDeepLink: UnwrapRef<typeof import('./composables/useDeepLink')['useDeepLink']>
    readonly useDevMode: UnwrapRef<typeof import('./composables/useDevMode')['useDevMode']>
    readonly useDeviceMotion: UnwrapRef<typeof import('@vueuse/core')['useDeviceMotion']>
    readonly useDeviceOrientation: UnwrapRef<typeof import('@vueuse/core')['useDeviceOrientation']>
    readonly useDevicePixelRatio: UnwrapRef<typeof import('@vueuse/core')['useDevicePixelRatio']>
    readonly useDevicesList: UnwrapRef<typeof import('@vueuse/core')['useDevicesList']>
    readonly useDisplayMedia: UnwrapRef<typeof import('@vueuse/core')['useDisplayMedia']>
    readonly useDocumentVisibility: UnwrapRef<typeof import('@vueuse/core')['useDocumentVisibility']>
    readonly useDraggable: UnwrapRef<typeof import('@vueuse/core')['useDraggable']>
    readonly useDraggableWindow: UnwrapRef<typeof import('./composables/useDraggableWindow')['useDraggableWindow']>
    readonly useDropZone: UnwrapRef<typeof import('@vueuse/core')['useDropZone']>
    readonly useDropdownPosition: UnwrapRef<typeof import('./composables/useDropdownPosition')['useDropdownPosition']>
    readonly useElementBounding: UnwrapRef<typeof import('@vueuse/core')['useElementBounding']>
    readonly useElementByPoint: UnwrapRef<typeof import('@vueuse/core')['useElementByPoint']>
    readonly useElementHover: UnwrapRef<typeof import('@vueuse/core')['useElementHover']>
    readonly useElementSize: UnwrapRef<typeof import('@vueuse/core')['useElementSize']>
    readonly useElementVisibility: UnwrapRef<typeof import('@vueuse/core')['useElementVisibility']>
    readonly useEventBus: UnwrapRef<typeof import('@vueuse/core')['useEventBus']>
    readonly useEventListener: UnwrapRef<typeof import('@vueuse/core')['useEventListener']>
    readonly useEventSource: UnwrapRef<typeof import('@vueuse/core')['useEventSource']>
    readonly useEyeDropper: UnwrapRef<typeof import('@vueuse/core')['useEyeDropper']>
    readonly useFavicon: UnwrapRef<typeof import('@vueuse/core')['useFavicon']>
    readonly useFetch: UnwrapRef<typeof import('@vueuse/core')['useFetch']>
    readonly useFileDialog: UnwrapRef<typeof import('@vueuse/core')['useFileDialog']>
    readonly useFileSystemAccess: UnwrapRef<typeof import('@vueuse/core')['useFileSystemAccess']>
    readonly useFocus: UnwrapRef<typeof import('@vueuse/core')['useFocus']>
    readonly useFocusWithin: UnwrapRef<typeof import('@vueuse/core')['useFocusWithin']>
    readonly useFps: UnwrapRef<typeof import('@vueuse/core')['useFps']>
    readonly useFullscreen: UnwrapRef<typeof import('@vueuse/core')['useFullscreen']>
    readonly useGamepad: UnwrapRef<typeof import('@vueuse/core')['useGamepad']>
    readonly useGeolocation: UnwrapRef<typeof import('@vueuse/core')['useGeolocation']>
    readonly useGlobalShortcuts: UnwrapRef<typeof import('./composables/useGlobalShortcuts')['useGlobalShortcuts']>
    readonly useGoogleFonts: UnwrapRef<typeof import('./composables/useGoogleFonts')['useGoogleFonts']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useIdle: UnwrapRef<typeof import('@vueuse/core')['useIdle']>
    readonly useImage: UnwrapRef<typeof import('@vueuse/core')['useImage']>
    readonly useInfiniteScroll: UnwrapRef<typeof import('@vueuse/core')['useInfiniteScroll']>
    readonly useIntersectionObserver: UnwrapRef<typeof import('@vueuse/core')['useIntersectionObserver']>
    readonly useInterval: UnwrapRef<typeof import('@vueuse/core')['useInterval']>
    readonly useIntervalFn: UnwrapRef<typeof import('@vueuse/core')['useIntervalFn']>
    readonly useKeyModifier: UnwrapRef<typeof import('@vueuse/core')['useKeyModifier']>
    readonly useLastChanged: UnwrapRef<typeof import('@vueuse/core')['useLastChanged']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLocalStorage: UnwrapRef<typeof import('@vueuse/core')['useLocalStorage']>
    readonly useMagicKeys: UnwrapRef<typeof import('@vueuse/core')['useMagicKeys']>
    readonly useManualRefHistory: UnwrapRef<typeof import('@vueuse/core')['useManualRefHistory']>
    readonly useMarkdown: UnwrapRef<typeof import('./composables/useMarkdown')['useMarkdown']>
    readonly useMediaControls: UnwrapRef<typeof import('@vueuse/core')['useMediaControls']>
    readonly useMediaQuery: UnwrapRef<typeof import('@vueuse/core')['useMediaQuery']>
    readonly useMemoize: UnwrapRef<typeof import('@vueuse/core')['useMemoize']>
    readonly useMemory: UnwrapRef<typeof import('@vueuse/core')['useMemory']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useMounted: UnwrapRef<typeof import('@vueuse/core')['useMounted']>
    readonly useMouse: UnwrapRef<typeof import('@vueuse/core')['useMouse']>
    readonly useMouseInElement: UnwrapRef<typeof import('@vueuse/core')['useMouseInElement']>
    readonly useMousePressed: UnwrapRef<typeof import('@vueuse/core')['useMousePressed']>
    readonly useMutationObserver: UnwrapRef<typeof import('@vueuse/core')['useMutationObserver']>
    readonly useNavigatorLanguage: UnwrapRef<typeof import('@vueuse/core')['useNavigatorLanguage']>
    readonly useNetwork: UnwrapRef<typeof import('@vueuse/core')['useNetwork']>
    readonly useNow: UnwrapRef<typeof import('@vueuse/core')['useNow']>
    readonly useObjectUrl: UnwrapRef<typeof import('@vueuse/core')['useObjectUrl']>
    readonly useOffsetPagination: UnwrapRef<typeof import('@vueuse/core')['useOffsetPagination']>
    readonly useOnline: UnwrapRef<typeof import('@vueuse/core')['useOnline']>
    readonly usePageLeave: UnwrapRef<typeof import('@vueuse/core')['usePageLeave']>
    readonly usePanelLayout: UnwrapRef<typeof import('./composables/usePanelLayout')['usePanelLayout']>
    readonly usePanelResize: UnwrapRef<typeof import('./composables/usePanelResize')['usePanelResize']>
    readonly usePanels: UnwrapRef<typeof import('./composables/usePanels')['usePanels']>
    readonly usePanelsStore: UnwrapRef<typeof import('./stores/panels')['usePanelsStore']>
    readonly useParallax: UnwrapRef<typeof import('@vueuse/core')['useParallax']>
    readonly useParentElement: UnwrapRef<typeof import('@vueuse/core')['useParentElement']>
    readonly usePerformanceObserver: UnwrapRef<typeof import('@vueuse/core')['usePerformanceObserver']>
    readonly usePermission: UnwrapRef<typeof import('@vueuse/core')['usePermission']>
    readonly usePermissions: UnwrapRef<typeof import('./composables/usePermissions')['usePermissions']>
    readonly usePinnedStore: UnwrapRef<typeof import('./stores/pinned')['usePinnedStore']>
    readonly usePointer: UnwrapRef<typeof import('@vueuse/core')['usePointer']>
    readonly usePointerLock: UnwrapRef<typeof import('@vueuse/core')['usePointerLock']>
    readonly usePointerSwipe: UnwrapRef<typeof import('@vueuse/core')['usePointerSwipe']>
    readonly usePreferencesStore: UnwrapRef<typeof import('./stores/preferences')['usePreferencesStore']>
    readonly usePreferredColorScheme: UnwrapRef<typeof import('@vueuse/core')['usePreferredColorScheme']>
    readonly usePreferredContrast: UnwrapRef<typeof import('@vueuse/core')['usePreferredContrast']>
    readonly usePreferredDark: UnwrapRef<typeof import('@vueuse/core')['usePreferredDark']>
    readonly usePreferredLanguages: UnwrapRef<typeof import('@vueuse/core')['usePreferredLanguages']>
    readonly usePreferredReducedMotion: UnwrapRef<typeof import('@vueuse/core')['usePreferredReducedMotion']>
    readonly usePreferredReducedTransparency: UnwrapRef<typeof import('@vueuse/core')['usePreferredReducedTransparency']>
    readonly usePrevious: UnwrapRef<typeof import('@vueuse/core')['usePrevious']>
    readonly useProjectContext: UnwrapRef<typeof import('./composables/useProjectContext')['useProjectContext']>
    readonly useProjectDirectory: UnwrapRef<typeof import('./composables/useProjectDirectory')['useProjectDirectory']>
    readonly useProjectStore: UnwrapRef<typeof import('./stores/project')['useProjectStore']>
    readonly useProviderAuth: UnwrapRef<typeof import('./composables/useProviderAuth')['useProviderAuth']>
    readonly useRafFn: UnwrapRef<typeof import('@vueuse/core')['useRafFn']>
    readonly useRefHistory: UnwrapRef<typeof import('@vueuse/core')['useRefHistory']>
    readonly useResizeObserver: UnwrapRef<typeof import('@vueuse/core')['useResizeObserver']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSSRWidth: UnwrapRef<typeof import('@vueuse/core')['useSSRWidth']>
    readonly useScreenOrientation: UnwrapRef<typeof import('@vueuse/core')['useScreenOrientation']>
    readonly useScreenSafeArea: UnwrapRef<typeof import('@vueuse/core')['useScreenSafeArea']>
    readonly useScriptTag: UnwrapRef<typeof import('@vueuse/core')['useScriptTag']>
    readonly useScroll: UnwrapRef<typeof import('@vueuse/core')['useScroll']>
    readonly useScrollLock: UnwrapRef<typeof import('@vueuse/core')['useScrollLock']>
    readonly useSessionStorage: UnwrapRef<typeof import('@vueuse/core')['useSessionStorage']>
    readonly useSettingsStore: UnwrapRef<typeof import('./stores/settings')['useSettingsStore']>
    readonly useShare: UnwrapRef<typeof import('@vueuse/core')['useShare']>
    readonly useShortcutStore: UnwrapRef<typeof import('./composables/useShortcutStore')['useShortcutStore']>
    readonly useSidebar: UnwrapRef<typeof import('./composables/useSidebar')['useSidebar']>
    readonly useSkills: UnwrapRef<typeof import('./composables/useSkills')['useSkills']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSorted: UnwrapRef<typeof import('@vueuse/core')['useSorted']>
    readonly useSource: UnwrapRef<typeof import('./composables/useSource')['useSource']>
    readonly useSpaceAutoInstall: UnwrapRef<typeof import('./composables/useSpaceAutoInstall')['useSpaceAutoInstall']>
    readonly useSpaceMarketplace: UnwrapRef<typeof import('./composables/useSpaceMarketplace')['useSpaceMarketplace']>
    readonly useSpacePreview: UnwrapRef<typeof import('./composables/useSpacePreview')['useSpacePreview']>
    readonly useSpaceShortcuts: UnwrapRef<typeof import('./composables/useSpaceShortcuts')['useSpaceShortcuts']>
    readonly useSpaces: UnwrapRef<typeof import('./composables/useSpaces')['useSpaces']>
    readonly useSpeechRecognition: UnwrapRef<typeof import('@vueuse/core')['useSpeechRecognition']>
    readonly useSpeechSynthesis: UnwrapRef<typeof import('@vueuse/core')['useSpeechSynthesis']>
    readonly useStepper: UnwrapRef<typeof import('@vueuse/core')['useStepper']>
    readonly useStorage: UnwrapRef<typeof import('./composables/useStorage')['useStorage']>
    readonly useStorageAsync: UnwrapRef<typeof import('@vueuse/core')['useStorageAsync']>
    readonly useStyleTag: UnwrapRef<typeof import('@vueuse/core')['useStyleTag']>
    readonly useSupported: UnwrapRef<typeof import('@vueuse/core')['useSupported']>
    readonly useSwipe: UnwrapRef<typeof import('@vueuse/core')['useSwipe']>
    readonly useTauriContext: UnwrapRef<typeof import('./composables/useTauriContext')['useTauriContext']>
    readonly useTelemetry: UnwrapRef<typeof import('./composables/useTelemetry')['useTelemetry']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTemplateRefsList: UnwrapRef<typeof import('@vueuse/core')['useTemplateRefsList']>
    readonly useTextDirection: UnwrapRef<typeof import('@vueuse/core')['useTextDirection']>
    readonly useTextSelection: UnwrapRef<typeof import('@vueuse/core')['useTextSelection']>
    readonly useTextareaAutosize: UnwrapRef<typeof import('@vueuse/core')['useTextareaAutosize']>
    readonly useThrottle: UnwrapRef<typeof import('@vueuse/core')['useThrottle']>
    readonly useThrottleFn: UnwrapRef<typeof import('@vueuse/core')['useThrottleFn']>
    readonly useThrottledRefHistory: UnwrapRef<typeof import('@vueuse/core')['useThrottledRefHistory']>
    readonly useTimeAgo: UnwrapRef<typeof import('@vueuse/core')['useTimeAgo']>
    readonly useTimeAgoIntl: UnwrapRef<typeof import('@vueuse/core')['useTimeAgoIntl']>
    readonly useTimeout: UnwrapRef<typeof import('@vueuse/core')['useTimeout']>
    readonly useTimeoutFn: UnwrapRef<typeof import('@vueuse/core')['useTimeoutFn']>
    readonly useTimeoutPoll: UnwrapRef<typeof import('@vueuse/core')['useTimeoutPoll']>
    readonly useTimestamp: UnwrapRef<typeof import('@vueuse/core')['useTimestamp']>
    readonly useTitle: UnwrapRef<typeof import('@vueuse/core')['useTitle']>
    readonly useToNumber: UnwrapRef<typeof import('@vueuse/core')['useToNumber']>
    readonly useToString: UnwrapRef<typeof import('@vueuse/core')['useToString']>
    readonly useToast: UnwrapRef<typeof import('./composables/useToast')['useToast']>
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>
    readonly useToolbar: UnwrapRef<typeof import('./composables/useToolbar')['useToolbar']>
    readonly useTransition: UnwrapRef<typeof import('@vueuse/core')['useTransition']>
    readonly useUpdater: UnwrapRef<typeof import('./composables/useUpdater')['useUpdater']>
    readonly useUrlSearchParams: UnwrapRef<typeof import('@vueuse/core')['useUrlSearchParams']>
    readonly useUserMedia: UnwrapRef<typeof import('@vueuse/core')['useUserMedia']>
    readonly useUserModule: UnwrapRef<typeof import('./composables/useUserModule')['useUserModule']>
    readonly useVModel: UnwrapRef<typeof import('@vueuse/core')['useVModel']>
    readonly useVModels: UnwrapRef<typeof import('@vueuse/core')['useVModels']>
    readonly useVibrate: UnwrapRef<typeof import('@vueuse/core')['useVibrate']>
    readonly useVirtualList: UnwrapRef<typeof import('@vueuse/core')['useVirtualList']>
    readonly useWakeLock: UnwrapRef<typeof import('@vueuse/core')['useWakeLock']>
    readonly useWebNotification: UnwrapRef<typeof import('@vueuse/core')['useWebNotification']>
    readonly useWebSocket: UnwrapRef<typeof import('@vueuse/core')['useWebSocket']>
    readonly useWebWorker: UnwrapRef<typeof import('@vueuse/core')['useWebWorker']>
    readonly useWebWorkerFn: UnwrapRef<typeof import('@vueuse/core')['useWebWorkerFn']>
    readonly useWindowChromeState: UnwrapRef<typeof import('./composables/useWindowChromeState')['useWindowChromeState']>
    readonly useWindowFocus: UnwrapRef<typeof import('@vueuse/core')['useWindowFocus']>
    readonly useWindowScroll: UnwrapRef<typeof import('@vueuse/core')['useWindowScroll']>
    readonly useWindowSize: UnwrapRef<typeof import('@vueuse/core')['useWindowSize']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchArray: UnwrapRef<typeof import('@vueuse/core')['watchArray']>
    readonly watchAtMost: UnwrapRef<typeof import('@vueuse/core')['watchAtMost']>
    readonly watchDebounced: UnwrapRef<typeof import('@vueuse/core')['watchDebounced']>
    readonly watchDeep: UnwrapRef<typeof import('@vueuse/core')['watchDeep']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchIgnorable: UnwrapRef<typeof import('@vueuse/core')['watchIgnorable']>
    readonly watchImmediate: UnwrapRef<typeof import('@vueuse/core')['watchImmediate']>
    readonly watchOnce: UnwrapRef<typeof import('@vueuse/core')['watchOnce']>
    readonly watchPausable: UnwrapRef<typeof import('@vueuse/core')['watchPausable']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly watchThrottled: UnwrapRef<typeof import('@vueuse/core')['watchThrottled']>
    readonly watchTriggerable: UnwrapRef<typeof import('@vueuse/core')['watchTriggerable']>
    readonly watchWithFilter: UnwrapRef<typeof import('@vueuse/core')['watchWithFilter']>
    readonly whenever: UnwrapRef<typeof import('@vueuse/core')['whenever']>
  }
}