/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentInput: typeof import('./components/agent/AgentInput.vue')['default']
    AgentView: typeof import('./components/agent/AgentView.vue')['default']
    AssistantPanel: typeof import('./components/ai/AssistantPanel.vue')['default']
    BottomPanel: typeof import('./components/panels/BottomPanel.vue')['default']
    Breadcrumb: typeof import('./components/toolbar/Breadcrumb.vue')['default']
    BuiltinWidgets: typeof import('./components/home/BuiltinWidgets.vue')['default']
    Button: typeof import('@construct-space/ui')['Button']
    ConfirmationModal: typeof import('./components/common/ConfirmationModal.vue')['default']
    CurrentUser4x2: typeof import('./components/home/widgets/CurrentUser4x2.vue')['default']
    DashboardPanel: typeof import('@construct-space/ui')['DashboardPanel']
    FileExplorer: typeof import('./components/panels/files/FileExplorer.vue')['default']
    FileTreeItem: typeof import('./components/panels/files/FileTreeItem.vue')['default']
    HomeGrid: typeof import('./components/home/HomeGrid.vue')['default']
    Icon: typeof import('@construct-space/ui')['Icon']
    MediaPickerModal: typeof import('./components/media/MediaPickerModal.vue')['default']
    MediaUploadModal: typeof import('./components/media/MediaUploadModal.vue')['default']
    Modal: typeof import('@construct-space/ui')['Modal']
    Notification: typeof import('@construct-space/ui')['Notification']
    OraclePanel: typeof import('./components/oracle/OraclePanel.vue')['default']
    RequestBubble: typeof import('./components/agent/RequestBubble.vue')['default']
    ResponseBlocks: typeof import('./components/agent/ResponseBlocks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/toolbar/Search.vue')['default']
    Sidebar3D: typeof import('./components/common/Sidebar3D.vue')['default']
    SplitPane: typeof import('./components/panels/SplitPane.vue')['default']
    SvgPreview: typeof import('./components/content/SvgPreview.vue')['default']
    Toolbar3D: typeof import('./components/common/Toolbar3D.vue')['default']
    ToolCard: typeof import('./components/agent/ToolCard.vue')['default']
    Tooltip: typeof import('@construct-space/ui')['Tooltip']
    WidgetChrome: typeof import('./components/home/WidgetChrome.vue')['default']
    WidgetPicker: typeof import('./components/home/WidgetPicker.vue')['default']
  }
}
